---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  MAPBOX_TOKEN: cGsuZXlKMWlKb2lZVzUxWkdWZWNEY2lMQ0poSWpvaVkyeDNhRzh5T0d4ak1HaDFaVEp6YjJObll6QnliemMyWmNKOS41bEdtZGNOdTNhWXBXTHA2RUVpZ0lB
  DB_URL: bW9uZ29kYitzcnY6Ly90aWVyYXBwdGVzdDc6c1hIcDZaQ1lZTjJOQlgwZkB0aWVyYXBwdGVzdC5oaW55azU5Lm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1UaWVyYXBwdGVzdAo=
  SECRET: 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: anudeep77/yelpgame:yelp
          ports:
            - containerPort: 3000
          env:
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
